services:
  - type: web
    name: underwater-detection-ui
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port $PORT
    autoDeploy: false
